import "../../globals.css";
import Sidebar from "@/components/SideBar/page";
import { Fragment } from "react";
export const metadata = {
  title: "AI Chat Bot",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: string;
}) {
  return (
    <Fragment>
      <Sidebar />
      <main className="bg-lightBackground dark:bg-gradient-to-t from-gradientLeft to-gradientRight px-12 mobileView:px-6 py-10 md:min-h-screen md:w-[calc(100%-300px)] md:float-right h-[100%] mobileView:pt-14 mobileView:w-full mobileView:min-h-screen">
        {children}
      </main>
    </Fragment>
  );
}
