export const ImagePath = {
    selectRadio: '/images/settingIcons/selectbtn.svg',
    unSelectRadio: '/images/settingIcons/unselect.svg',
    checkedIcon: '/images/checkboxicon.svg',
    CardIcon: "/images/visaimage.svg",
    DeleteIcon: "/images/delete.svg"
}

export const LightImage = {
    whiteAuth: '/images/auth.svg',
    whiteMenu: '/images/menuicon.svg',
    whiteCross: '/images/sidebarIcons/cross.svg',
    whiteLogoText: '/images/sidebarIcons/logotext.svg',
    whiteChat: '/images/sidebarIcons/chat.svg',
    whiteSubscription: '/images/sidebarIcons/subscriptionicon.svg',
    whiteHelpSupport: '/images/sidebarIcons/help&support.svg',
    whiteTermsIcon: '/images/sidebarIcons/termsicon.svg',
    whitePrivacy: '/images/sidebarIcons/privacyicon.svg',
    whiteSetting: '/images/sidebarIcons/settings.svg',
    whiteLogout: '/images/sidebarIcons/logout.svg',
    whiteDownArrow: '/images/downarrow.svg',
    whiteLeftArrow: '/images/leftarrow.svg',
    whiteUserIcon: '/images/user.svg',
    whiteEditIcon: '/images/edit.svg',
    whiteMailIcon: '/images/mailicon.svg',
    lightToggle: '/images/settingIcons/btnlight.svg',
    whiteCahtMenu: '/images/slidebarwhite.svg',
    darkChatIcon: '/images/chat.svg',
    whiteMobile: '/images/mobile.svg',
    whiteLoginIcon: '/images/loginimage.svg',
    whiteAddPayment: '/images/settingIcons/addpayment.svg',
    whitePaymentHistory: '/images/settingIcons/paymenthis.svg',
    whiteLanguage: '/images/settingIcons/changelanguagenew.svg',
    whitecolorTheme: '/images/settingIcons/colorchanges.svg',
    whiteEditProfile: '/images/settingIcons/editprofilenew.svg',
    whiteToggle: '/images/settingIcons/btnlight.svg',
    whiteDownload: '/images/uploadicon.svg',
    whiteNoti:'/images/notification.svg',
    whiteDownloadIcon:'/images/downloadicon.svg',
}

export const DarkImage = {
    darkAuth:'/images/lighticon/authblack.svg',
    darkToggle: '/images/settingIcons/buttondark.svg',
    darkChat: '/images/lighticon/chathistory.svg',
    darkSubscription: '/images/lighticon/currentsubscription.svg',
    darkHelp: '/images/lighticon/help.svg',
    darkTerms: '/images/lighticon/terms.svg',
    darkPrivacy: '/images/lighticon/privacy.svg',
    darkSetting: '/images/lighticon/setting.svg',
    darkLogout: '/images/lighticon/logout.svg',
    darkAddPay:'/images/lighticon/addpayment.svg',
    darkPayment:'/images/lighticon/payment.svg',
    darkLang:'/images/lighticon/language.svg',
    darkTheme:'/images/lighticon/colortheme.svg',
    darkProfile:'/images/lighticon/editprofilenew.svg',
    darkDropdown:'/images/lighticon/downarrow.svg',
    darkLeftArrow:'/images/lighticon/leftblackarrow.svg',
    darkMail:'/images/lighticon/blackmailicon.svg',
    darkMobile:'/images/lighticon/blackMobile.svg',
    darkChatMenu:'/images/lighticon/slidebarblack.svg',
    darkLogo:'/images/lighticon/logoblack.svg',
    darkUser:'/images/lighticon/userblack.svg',
    darkEdit:'/images/lighticon/editblack.svg',
    darkNoti:'/images/lighticon/notificationBlack.svg',
}