import { ThemeProvider } from "@/app/theme-provider";
import "./globals.css";
import CheckUser from "@/components/context";
import { Providers } from "@/redux/provider";
import { ThemeSwitcher } from "@/components/ThemeSwitcher";
export const metadata = {
  title: "AI Chat Bot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />

        {/* <Script
          defer
          src="https://www.gstatic.com/firebasejs/8.10.1/firebase-app.js"
        ></Script> */}

        {/* <Script defer src="../firebase/config"></Script> */}
      </head>
      <body className="overflow-x-hidden">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ThemeSwitcher />
          <CheckUser>
            <Providers>{children}</Providers>
          </CheckUser>
        </ThemeProvider>

        {/* <Script src="https://www.gstatic.com/firebasejs/4.2.0/firebase-messaging.js"></Script> */}
      </body>
    </html>
  );
}
