import "./globals.css";
import CheckUser from "@/components/context";
import { Providers } from "@/redux/provider";
export const metadata = {
  title: "AI Chat Bot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="overflow-x-hidden">
        <CheckUser>
          <Providers>{children}</Providers>
        </CheckUser>
      </body>
    </html>
  );
}
