
import Sidebar from "@/components/SideBar/page";
import ChatHistory from "@/pages/Dashboard/Chat/ChatHistory";
import ChatUserDetail from "@/pages/Dashboard/Chat/ChatUserDetail";
import NewChat from "@/pages/Dashboard/Chat/NewChat";
import DashboardHeading from "@/pages/Dashboard/Heading";
import { Fragment,useEffect } from "react";

export const metadata = {
  title: "AI Chat Bot",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: string;
}) {
  return (
    <Fragment>
      <DashboardHeading heading="Chat History">
        <section className="mt-10 tablet:mt-3 fixed w-[-webkit-fill-available]">
          <div className="flex pr-5">
            <input type="checkbox" id="menuOpen" className="hidden peer" />
            {children}
          </div>
        </section>
      </DashboardHeading>
    </Fragment>
  );
}
