"use client";
import DashboardHeading from "@/pages/Dashboard/Heading";

const PrivacyPolicy = () => {
  return (
    <DashboardHeading heading="Privacy Policy">
     
        <div className="bg-white dark:bg-themeBg px-5 py-5 mt-10">
          <p className="text-black dark:text-white font-['Poppins'] text-lg tablet:text-base xxxs:text-sm">
            Welcome to our AI Chat Application! These Terms and Conditions
            outline the rules and regulatios for the use of our services. By
            accessing or using our AI Chat Application , You agree to comply
            with these Terms and Conditions. Plesae read them carefully before
            using our services.
          </p>
          <ol className="text-black dark:text-white font-['Poppins'] text-lg tablet:text-base xxxs:text-sm">
            <li className="flex items-baseline leading-8 mt-3">
              <p className="mr-3">1</p>Acceptance of Termsa
            </li>
            <li className="flex items-baseline leading-8 mt-3">
              <p className="mr-3">2</p>1.1. By using our AI Chat Application,
              you acknowledge that you have read, understood, and agreed to be
              bound by these Terms and Conditions.
            </li>
            <li className="flex items-baseline leading-8 mt-3">
              <p className="mr-3">3</p>1.2. If you do not agree with any part of
              these Terms and Condition, please do not use our services.
            </li>
            <li className="flex items-baseline leading-8 mt-3">
              <p className="mr-3">4</p>Use of the AI Chat Application
            </li>
            <li className="flex items-baseline leading-8 mt-3">
              <p className="mr-3">5</p>2.1. The AI Chat Application provides an
              intractive chat experience using artificial intelligence.
            </li>
            <li className="flex items-baseline leading-8 mt-3">
              <p className="mr-3">6</p>2.2. You must be at least 18 years old or
              have the consent of a parent or legal guardian to use our
              services.
            </li>
            <li className="flex items-baseline leading-8 mt-3">
              <p className="mr-3">7</p>2.3. You are responsible for maintaining
              the confidentiality of your account and password. You agree to
              notify us immediatly of any unauthorized use of your account.{" "}
            </li>
            <li className="flex items-baseline leading-8 mt-3">
              <p className="mr-3">8</p>2.4. You understand and acknowledge that
              the responses provided by the AI Chat Application are generated by
              artificial intelligence and may not always be accurate or
              reliable.
            </li>
            <li className="flex items-baseline leading-8 mt-3">
              <p className="mr-3">9</p>2.5. You agree not to use the AI Chat
              Appliaction for any illegal , harmful, or malicious activities.
            </li>
          </ol>
        </div>
    </DashboardHeading>
  );
};
export default PrivacyPolicy;
